name: Release
on:
  push:
    tags:
      - v*
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build.yml
  documentation:
    permissions: write-all
    uses: ./.github/workflows/documentation.yml
  release:
    name: Create Release
    permissions: write-all
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Download artifacts for ankaios-linux-amd64-bin
        uses: actions/download-artifact@v3.0.2
        with:
          name: ankaios-linux-amd64-bin
          path: dist/linux-amd64/bin
      - name: Download artifacts for ankaios-linux-arm64-bin
        uses: actions/download-artifact@v3.0.2
        with:
          name: ankaios-linux-arm64-bin
          path: dist/linux-arm64/bin
      - name: Download artifacts for requirement-tracing-report
        uses: actions/download-artifact@v3.0.2
        with:
          name: requirement-tracing-report
          path: dist/
      - name: Download artifacts for code-coverage
        uses: actions/download-artifact@v3.0.2
        with:
          name: code-coverage
          path: dist/coverage
      - name: Package release artifacts
        run: tools/create_release.sh
      - name: Upload release artifacts
        run: |
          cd dist
          tree
          gh release upload ${{ github.ref_name }} coverage-report.tar.gz \
          coverage-report.zip \
          req_tracing_report.html \
          install.sh \
          ankaios.proto \
          linux-amd64/ankaios-linux-amd64.tar.gz \
          linux-amd64/ankaios-linux-amd64.tar.gz.sha512sum.txt \
          linux-arm64/ankaios-linux-arm64.tar.gz \
          linux-arm64/ankaios-linux-arm64.tar.gz.sha512sum.txt

  build_and_publish_app_devcontainer_base:
    name: Publish app devcontainer base
    needs: release
    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Get TAG
        id: get_tag
        run: echo TAG=${GITHUB_REF#refs/tags/v} >> $GITHUB_ENV
      - name: Get Repo Owner
        id: get_repo_owner
        run: echo "REPO_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" > $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: Release app devcontainer base
        id: release_app_devconatiner_base
        uses: docker/build-push-action@v4
        with:
          context: 'tools/app_dev_container_base'
          outputs: "type=registry,push=true"
          provenance: false
          platforms: linux/amd64,linux/arm64
          build-args: |
            Version=${{  env.TAG }}
            GitCommit=${{ github.sha }}
          tags: |
            ghcr.io/${{ env.REPO_OWNER }}/app-ankaios-dev:${{ github.sha }}
            ghcr.io/${{ env.REPO_OWNER }}/app-ankaios-dev:${{ env.TAG }}
            ghcr.io/${{ env.REPO_OWNER }}/app-ankaios-dev:latest
